name: deploy

on:
  push:
    branches:
      - main
      - x

jobs:
  docker:
    if: github.event_name == 'push'
    needs: run-tests-2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Version extraction
        id: get_version
        run: echo "::set-output name=version::$(cat version)"
      - name: Building & tagging
        run: docker build -t ashgw/litecrypt:${{ steps.get_version.outputs.version }} scripts/docker-build
      - name: Login
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ashgw --password-stdin
      - name: Pushing to the hub
        run: docker push ashgw/litecrypt:${{ steps.get_version.outputs.version }}
